/*
 * Ethereum`s web3 constants
 */


// Statuses

export const WEB3__CONNECTION_STATUS__NOT_INITIALIZED    = 'Jibrel/web3/CONNECTION_STATUS__NOT_INITIALIZED';
export const WEB3__CONNECTION_STATUS__CONNECTION_ATTEMPT = 'Jibrel/web3/CONNECTION_STATUS__CONNECTION_ATTEMPT';
export const WEB3__CONNECTION_STATUS__SUCCESS            = 'Jibrel/web3/CONNECTION_STATUS__SUCCESS';
export const WEB3__CONNECTION_STATUS__FAILURE            = 'Jibrel/web3/CONNECTION_STATUS__FAILURE';

export const WEB3__NETWORK_STATUS__NOT_INITIALIZED = 'Jibrel/web3/NETWORK_STATUS__NOT_INITIALIZED';
export const WEB3__NETWORK_STATUS__REQUEST_SENT    = 'Jibrel/web3/NETWORK_STATUS__REQUEST_SENT';
export const WEB3__NETWORK_STATUS__SUCCESS         = 'Jibrel/web3/NETWORK_STATUS__SUCCESS';
export const WEB3__NETWORK_STATUS__FAILURE         = 'Jibrel/web3/NETWORK_STATUS__FAILURE';

export const WEB3__ACCOUNTS_STATUS__NOT_INITIALIZED = 'Jibrel/web3/ACCOUNTS_STATUS__NOT_INITIALIZED';
export const WEB3__ACCOUNTS_STATUS__REQUEST_SENT    = 'Jibrel/web3/ACCOUNTS_STATUS__REQUEST_SENT';
export const WEB3__ACCOUNTS_STATUS__SUCCESS         = 'Jibrel/web3/ACCOUNTS_STATUS__SUCCESS';
export const WEB3__ACCOUNTS_STATUS__FAILURE         = 'Jibrel/web3/ACCOUNTS_STATUS__FAILURE';

export const WEB3__PROVIDER_TYPE__INJECTED = 'Jibrel/web3/PROVIDER_TYPE__INJECTED';
export const WEB3__PROVIDER_TYPE__TESTRPC  = 'Jibrel/web3/PROVIDER_TYPE__TESTRPC';


// Actions

export const WEB3__INIT_CONNECTION        = 'Jibrel/web3/INIT_CONNECTION';
export const WEB3__CONNECTION_INITIALIZED = 'Jibrel/web3/CONNECTION_INITIALIZED';
export const WEB3__CONNECTION_FAILED      = 'Jibrel/web3/CONNECTION_FAILED';

export const WEB3__LAUNCH_NETWORK_POLLING = 'Jibrel/web3/LAUNCH_NETWORK_POLLING';
export const WEB3__NETWORK_SUCCESS        = 'Jibrel/web3/NETWORK_SUCCESS';
export const WEB3__NETWORK_FAILURE        = 'Jibrel/web3/NETWORK_FAILURE';

export const WEB3__LAUNCH_ACCOUNTS_POLLING = 'Jibrel/web3/LAUNCH_ACCOUNTS_POLLING';
export const WEB3__ACCOUNTS_SUCCESS        = 'Jibrel/web3/ACCOUNTS_SUCCESS';
export const WEB3__ACCOUNTS_FAILURE        = 'Jibrel/web3/ACCOUNTS_FAILURE';

